name: flutter_sunmi_printer
description: Flutter plugin allows to print thermal receipts using Sunmi device with a built-in printer
version: 0.2.1
homepage: https://github.com/andrey-ushakov/flutter_sunmi_printer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_sunmi_printer
        pluginClass: FlutterSunmiPrinterPlugin
      ios:
        pluginClass: FlutterSunmiPrinterPlugin
